name: e_commerce_app
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.15.0-268.0.dev <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  get: ^4.6.1
  firebase_core: ^1.10.6
  firebase_auth: ^3.3.4
  google_sign_in: ^5.2.1
  flutter_login_facebook: ^1.2.0
  cloud_firestore: ^3.1.5
  salomon_bottom_bar: ^3.2.0
  sqflite: ^2.0.1
  path: ^1.8.0
  flutter_svg: ^1.0.0

  flutter_lints: ^1.0.0


flutter:

  
  uses-material-design: true

  